name: 🪳 Bug
description: I need to report a Bug 🚨
title: 🪳
labels: ["app", "problem"]
assignees:
  - robertococco
body:
  - type: checkboxes
    id: rules
    attributes:
      label: Before you Continue
      description: Do you respect the following rule?
      options:
        - label: I wrote an explanatory and conicise title which start with 🪳
          required: true
  - type: textarea
    id: bug-report
    attributes:
      label: I would like to talk about a Feature
      placeholder: Tell us everything about it!
    validations:
      required: true
