name: 📄 Docs
description: I would like to talk about Docs
labels: ["doc"]
assignees:
  - robertococco
body:
  - type: textarea
    id: docsAbout
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: labels
    attributes:
      label: Before Submit
      description: You must put one of the follows labels (proposal, problem, question)
      options:
        - label: I put one of the follows labels (proposal, problem, question)
          required: true
