name: 📄 Docs
description: I would like to talk about Docs
labels: ["doc"]
assignees:
  - robertococco
body:
  - type: checkboxes
    id: labels
    attributes:
      label: Before Submit
      description: Do you respect the following rules?
      options:
        - label: I wrote an explanatory and conicise title
          required: true
        - label: I added one of the following labels (proposal, problem, question)
          required: true
  - type: textarea
    id: docs-about
    attributes:
      label: I would like to talk about Docs
      placeholder: Tell us everything about it!
    validations:
      required: true
