name: 🚀 Feature
description: I have an idea 🧠
title: "[🚀 Feature] "
labels: ["app", "proposal"]
assignees:
  - robertococco
body:
  - type: checkboxes
    id: rules
    attributes:
      label: Before you Continue
      description: Do you respect the following rule?
      options:
        - label: "I wrote an explanatory and conicise title which start with [🚀 Feature]"
          required: true
  - type: textarea
    id: feature-prupose
    attributes:
      label: The idea
      placeholder: Tell us everything about it!
    validations:
      required: true
