name: 🚩 Help
description: I Need Support!
title: 🚩 Help |
labels: ["triage", "help"]
assignees:
  - robertococco
body:
  - type: checkboxes
    id: rules
    attributes:
      label: ❗ Before you Continue
      description: Do you respect the following rules?
      options:
        - label: I wrote an explanatory and conicise title after the "|" symbol
          required: true
        - label: I added one of the following labels (scope:app, scope:doc)
          required: true
  - type: textarea
    id: docs-about
    attributes:
      label: 🚩 I Need Support
      placeholder: Tell us everything about it!
    validations:
      required: true
