name: 💥 Problem
description: Something went wrong!
title: 💥 Problem |
labels: ["triage", "problem"]
assignees:
  - robertococco
body:
  - type: checkboxes
    id: rules
    attributes:
      label: ❗ Before you Continue
      description: Do you respect the following rule?
      options:
        - label: I wrote an explanatory and conicise title after the "|" symbol
          required: true
        - label: I added one of the following labels (scope:app, scope:doc)
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What Happen?
      placeholder: Tell us what happen!
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What you Expect?
      placeholder: Tell us what you expect!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
